-- 원유 모의투자 · 저장창고 준비 (Supabase 의 SQL Editor 에서 한 번 실행)
-- · 잔고는 wallet2 표의 balance 칸에 넣는다 (이미 만들어 두셨으면 그 표를 그대로 쓰고, 없으면 만든다)
-- · 주문 기록은 oil_ 을 붙인 새 표(oil_orders)에 넣어서 이 프로젝트의 다른 표(wallet, orders 등)와 겹치지 않는다
-- · 가지고 있는 원유 수량은 따로 저장하지 않고 주문 기록(산 것 - 판 것)으로 계산한다
-- · 여러 번 실행해도 안전하다 (이미 있으면 그대로 두고, 함수만 새로 덮어쓴다)
-- · 지갑은 하나뿐이고 시작 잔고는 $1,000 이다

-- 1) 표 준비 -------------------------------------------------------------------
-- 잔고 표: 이미 있으면 건드리지 않는다
create table if not exists wallet2 (
  id         bigint generated by default as identity primary key,
  balance    numeric(20,4) not null default 1000,   -- 잔고 (달러)
  created_at timestamptz not null default now()
);

-- 잔고 칸이 정수·소수(부동소수) 모양이면 센트까지 정확한 숫자 모양으로 바꾼다 (이미 맞으면 그대로)
do $$
begin
  if (select data_type from information_schema.columns
      where table_schema = 'public' and table_name = 'wallet2' and column_name = 'balance') <> 'numeric' then
    alter table wallet2 alter column balance type numeric(20,4) using balance::numeric;
  end if;
end $$;
alter table wallet2 alter column balance set default 1000;

create table if not exists oil_orders (
  id         serial primary key,
  created_at timestamptz not null default now(),   -- 시간
  market     text not null,                        -- 어떤 원유 (wti, brent, dubai)
  side       text not null check (side in ('buy', 'sell')),   -- 매수 / 매도
  qty        integer not null check (qty > 0),     -- 수량 (배럴)
  price      numeric(20,4) not null,               -- 체결가
  amount     numeric(20,4) not null,               -- 체결가 x 수량
  memo       text                                  -- 왜 샀는지(팔았는지) 한 줄
);

create index if not exists oil_orders_time on oil_orders (created_at desc, id desc);

-- 2) 잠금: 표를 직접 열어 보거나 고치지 못하게 막는다 (정책을 하나도 안 만든다 = 모두 거절)
--    Supabase 화면(Table Editor)에서 보는 것은 그대로 된다. 앱은 아래 함수를 통해서만 만진다
alter table wallet2 enable row level security;
alter table oil_orders enable row level security;
revoke all on table wallet2, oil_orders from anon, authenticated;

-- 3) 함수 4개 ------------------------------------------------------------------

-- (안쪽에서만 쓰는 도우미) 가지고 있는 원유 수량 = 산 것 - 판 것. 예: {"wti": 3, "brent": 2}
create or replace function oil_holdings()
returns jsonb language sql security definer set search_path = public as $$
  select coalesce(jsonb_object_agg(market, qty), '{}'::jsonb)
  from (
    select market, sum(case side when 'buy' then qty else -qty end)::integer as qty
    from oil_orders
    group by market
    having sum(case side when 'buy' then qty else -qty end) > 0
  ) t;
$$;

-- 내 지갑: wallet2 의 첫 줄이 내 지갑이다 (아직 한 줄도 없으면 잔고 $1,000 으로 만든다)
create or replace function oil_get_wallet()
returns json language plpgsql security definer set search_path = public as $$
declare
  w wallet2;
begin
  perform pg_advisory_xact_lock(hashtext('oil_wallet2'));   -- 동시에 처음 열어도 지갑이 두 개 생기지 않게
  select * into w from wallet2 order by created_at, id limit 1;
  if not found then
    insert into wallet2 (balance) values (1000) returning * into w;
  end if;
  return json_build_object('cash', coalesce(w.balance, 0), 'holdings', oil_holdings());
end $$;

-- 주문 내역 (새 것부터, 최대 200건)
create or replace function oil_list_orders(p_limit integer default 50)
returns json language sql security definer set search_path = public as $$
  select coalesce(json_agg(o order by o.created_at desc, o.id desc), '[]'::json)
  from (
    select id, created_at, market, side, qty, price, amount, memo
    from oil_orders
    order by created_at desc, id desc
    limit least(greatest(coalesce(p_limit, 50), 1), 200)
  ) o;
$$;

-- 사기 · 팔기: 현재가로 체결하고, wallet2 잔고를 빼거나(사기) 더하고(팔기), 주문 한 줄을 남긴다
-- 지갑 줄을 잠그고 한 번에 처리해서 동시에 눌러도 꼬이지 않는다. 잔고나 원유가 모자라면 거절한다
create or replace function oil_place_order(p_market text, p_side text, p_qty integer, p_price numeric, p_memo text default null)
returns json language plpgsql security definer set search_path = public as $$
declare
  w          wallet2;
  o          oil_orders;
  held_qty   integer := 0;
  v_amount   numeric;
  v_cash     numeric;
  v_memo     text := nullif(left(btrim(coalesce(p_memo, '')), 200), '');
begin
  if p_side is null or p_side not in ('buy', 'sell') then raise exception '사기는 buy, 팔기는 sell 로 보내 주세요.'; end if;
  if p_qty is null or p_qty < 1 then raise exception '수량은 1 이상의 정수여야 해요.'; end if;
  if p_price is null or p_price <= 0 then raise exception '가격이 올바르지 않아요.'; end if;
  if p_market is null or p_market !~ '^[a-z]{2,20}$' then raise exception '원유 이름이 올바르지 않아요.'; end if;

  perform pg_advisory_xact_lock(hashtext('oil_wallet2'));
  select * into w from wallet2 order by created_at, id limit 1 for update;
  if not found then
    insert into wallet2 (balance) values (1000) returning * into w;
  end if;

  held_qty := coalesce((oil_holdings() ->> p_market)::integer, 0);
  v_amount := round(p_qty * p_price, 4);

  if p_side = 'buy' then
    if v_amount > coalesce(w.balance, 0) + 0.000001 then
      raise exception '돈이 모자라요. 쓸 수 있는 돈은 $%예요.', to_char(coalesce(w.balance, 0), 'FM999,999,990.00');
    end if;
    v_cash := round(coalesce(w.balance, 0) - v_amount, 4);   -- 사면 잔고가 줄어든다
  else
    if p_qty > held_qty then
      raise exception '가진 원유가 모자라요. 지금 %배럴 가지고 있어요.', held_qty;
    end if;
    v_cash := round(coalesce(w.balance, 0) + v_amount, 4);   -- 팔면 잔고가 늘어난다
  end if;

  insert into oil_orders (market, side, qty, price, amount, memo)
  values (p_market, p_side, p_qty, p_price, v_amount, v_memo)
  returning * into o;

  update wallet2 set balance = v_cash where id = w.id returning * into w;

  return json_build_object(
    'order', json_build_object('id', o.id, 'created_at', o.created_at, 'market', o.market, 'side', o.side,
                               'qty', o.qty, 'price', o.price, 'amount', o.amount, 'memo', o.memo),
    'wallet', json_build_object('cash', w.balance, 'holdings', oil_holdings()));
end $$;

-- 4) 권한: 서버가 쓰는 공개용 열쇠(anon)로 함수 3개만 부를 수 있다 (도우미 oil_holdings 는 못 부른다)
revoke all on function oil_holdings() from public, anon, authenticated;
revoke all on function oil_get_wallet() from public;
revoke all on function oil_list_orders(integer) from public;
revoke all on function oil_place_order(text, text, integer, numeric, text) from public;
grant execute on function oil_get_wallet() to anon, authenticated;
grant execute on function oil_list_orders(integer) to anon, authenticated;
grant execute on function oil_place_order(text, text, integer, numeric, text) to anon, authenticated;

-- 5) 방금 만든 함수를 API 가 바로 알아보게 한다
notify pgrst, 'reload schema';

-- (처음부터 다시 하고 싶을 때만 아래 두 줄을 따로 실행. delete 에는 where 가 꼭 있어야 한다)
-- delete from oil_orders where true;
-- update wallet2 set balance = 1000 where true;
